package pb.repo.admin.constant;

public class AdminConstant {
	public static final StringBuffer CHANGE_LOG = new StringBuffer();
	
	public static final String VERSION = "1.0.42";
	
    static {
//		CHANGE_LOG.append("  - Interface : Use user_id to call service\n");
//		CHANGE_LOG.append("  - Interface : For Odoo : Manage Member in Accounting Group\n");
//		CHANGE_LOG.append("  - Workflow : Admin Adhoc Task\n");
    	CHANGE_LOG.append("\nV."+AdminConstant.VERSION+" --- (21/07/2016)\n");
		CHANGE_LOG.append("  - PR Approval Matrix : Project Type\n");
		CHANGE_LOG.append("  - PR Form : Committee : Chairman Label\n");
		CHANGE_LOG.append("  - PR Form : Edit : Enable Currency Rate field if it is not 'THB'\n");
		CHANGE_LOG.append("  - PR Form : Additional PR : Clear Ref PR No. field if uncheck the checkbox\n");
    	CHANGE_LOG.append("\nV.1.0.41 --- (20/07/2016)\n");
		CHANGE_LOG.append("  - PD Interface : Action=1 : Check duplicated data\n");
		CHANGE_LOG.append("  - PD Interface : Action=3 : Remove Approver from History\n");
		CHANGE_LOG.append("  - Workflow : Tell the reason for rejecting in the comment field\n");
		CHANGE_LOG.append("  - PR Interface : Send Price instead of Converted Price\n");
		CHANGE_LOG.append("  - PD Workflow : Last Approver signature\n");
		CHANGE_LOG.append("  - PD Interface : Add Approver Permission to PD Folder\n");
    	CHANGE_LOG.append("\nV.1.0.40 --- (15/07/2016)\n");
		CHANGE_LOG.append("  - PR Form : User Tab : Multiple Language Label\n");
		CHANGE_LOG.append("  - PD Workflow : Add Approver into history\n");
    	CHANGE_LOG.append("\nV.1.0.39 --- (13/07/2016)\n");
		CHANGE_LOG.append("  - PR Form : Check Duplicated Committee\n");
		CHANGE_LOG.append("  - AV Interface : Fill Parameters from UI Input\n");
		CHANGE_LOG.append("  - UI : Multiple Languages\n");
    	CHANGE_LOG.append("\nV.1.0.38 --- (12/07/2016)\n");
		CHANGE_LOG.append("  - PR Form : Error Msg\n");
    	CHANGE_LOG.append("\nV.1.0.37 --- (12/07/2016)\n");
		CHANGE_LOG.append("  - AV Form : List Old AV\n");
		CHANGE_LOG.append("  - PD Interface : Change method from create to action\n");
    	CHANGE_LOG.append("\nV.1.0.36 --- (12/07/2016)\n");
		CHANGE_LOG.append("  - PR Form : Check Mandatory Equiment field\n");
		CHANGE_LOG.append("  - PR Form : Update Error Messages\n");
		CHANGE_LOG.append("  - PD Interface : Add Comment Field\n");
    	CHANGE_LOG.append("\nV.1.0.35 --- (11/07/2016)\n");
		CHANGE_LOG.append("  - PR Interface : Add Reason field\n");
		CHANGE_LOG.append("  - AV Form : Update table detail\n");
		CHANGE_LOG.append("  - AV : Remove field activity\n");
    	CHANGE_LOG.append("\nV.1.0.34 --- (08/07/2016)\n");
		CHANGE_LOG.append("  - PR,AV,AP Form : Change Budget Source Label\n");
		CHANGE_LOG.append("  - PR Form : Change Across Budget Label\n");
		CHANGE_LOG.append("  - PR Form : Change Location Label\n");
		CHANGE_LOG.append("  - PR Form : Change Old PR Label\n");
		CHANGE_LOG.append("  - PR Form : Change Price Label\n");
		CHANGE_LOG.append("  - PR,AV,AP Form : Budget Source : Main Equipment Explanation icon\n");
		CHANGE_LOG.append("  - AV : Add table detail\n");
    	CHANGE_LOG.append("\nV.1.0.33 --- (07/07/2016)\n");
		CHANGE_LOG.append("  - AV Form : Change Activity Combo Box to Text Area\n");
		CHANGE_LOG.append("  - AV Table : Change Activity Field Type from integer to varchar\n");
		CHANGE_LOG.append("  - PD Workflow : Comment History : Remove Doc Type from Comment\n");
		CHANGE_LOG.append("  - PR Form : Cross Year Budget : Filter Purchase Method\n");
    	CHANGE_LOG.append("\nV.1.0.32 --- (06/07/2016)\n");
		CHANGE_LOG.append("  - Main : Change MAIN_ODOO_URL and MAIN_ODOO_DB to PCM_* and EXP_*\n");
		CHANGE_LOG.append("  - PR Form : Line Item : Remove 'Type' Column\n");
		CHANGE_LOG.append("  - Interface : Create AV\n");
		CHANGE_LOG.append("  - AV,AP : Add Column employee position id for Interface\n");
		CHANGE_LOG.append("  - PR Interface : delete parameter purchase_confidential_id.id\n");
		CHANGE_LOG.append("  - PR Interface : change parameter confidential_detail to purchase_condition_detail\n");
    	CHANGE_LOG.append("\nV.1.0.31 --- (05/07/2016)\n");
		CHANGE_LOG.append("  - PD Interface : Resubmit and cancel from Odoo\n");
		CHANGE_LOG.append("  - PR Form : Read Method Cond2 from table\n");
    	CHANGE_LOG.append("\nV.1.0.30 --- (30/06/2016)\n");
		CHANGE_LOG.append("  - Workflow Table : add field 'execution_id'\n");
		CHANGE_LOG.append("  - Admin : System Config : MAIN_INF_PD_UPDATE_STATUS\n");
		CHANGE_LOG.append("  - AP : Copy : Clear Employee AV : Clear AV Id\n");
		CHANGE_LOG.append("  - AV,AP Form : Add Requester Tel NO. field\n");
    	CHANGE_LOG.append("\nV.1.0.29 --- (27/06/2016)\n");
		CHANGE_LOG.append("  - PD : Search Approval Matrix\n");
    	CHANGE_LOG.append("\nV.1.0.28 --- (22/06/2016)\n");
		CHANGE_LOG.append("  - Consult : Comment Required\n");
		CHANGE_LOG.append("  - PR : Send for Approval : Missing Attached Files\n");
		CHANGE_LOG.append("  - PR Form : Add Field Request Tel NO.\n");
		CHANGE_LOG.append("  - PR Pdf : Add Field Request Tel NO.\n");
    	CHANGE_LOG.append("\nV.1.0.27 --- (21/06/2016)\n");
		CHANGE_LOG.append("  - PR,AV,AP Form : Search Section : Add Column Cost Center\n");
		CHANGE_LOG.append("  - AP Form : Change comply to meeting requirement\n");
		CHANGE_LOG.append("  - Search : Google Style\n");
		CHANGE_LOG.append("  - PR : Change Committee Input Dialog\n");
    	CHANGE_LOG.append("\nV.1.0.26 --- (14/06/2016)\n");
		CHANGE_LOG.append("  - AP Form : Preview\n");
		CHANGE_LOG.append("  - AV Form : Preview\n");
		CHANGE_LOG.append("  - Main Menu : Change Labels\n");
		CHANGE_LOG.append("  - Interface : Create PR Interface : Wrong Assignee\n");
    	CHANGE_LOG.append("\nV.1.0.25 --- (13/06/2016)\n");
		CHANGE_LOG.append("  - AP Form : Activity Detail is not mandatory if no choice to select\n");
		CHANGE_LOG.append("  - AP Form : Edit Activity\n");
    	CHANGE_LOG.append("\nV.1.0.24 --- (10/06/2016)\n");
		CHANGE_LOG.append("  - AP Form : Tab Attendee : Show Cost Control\n");
		CHANGE_LOG.append("  - AP Form : Tab Info : Combo Boxes don't show Bank list\n");
    	CHANGE_LOG.append("\nV.1.0.23 --- (09/06/2016)\n");
		CHANGE_LOG.append("  - AP Form : Save Draft\n");
		CHANGE_LOG.append("  - AV Form : Copy AV Button\n");
    	CHANGE_LOG.append("\nV.1.0.22 --- (07/06/2016)\n");
		CHANGE_LOG.append("  - AV Form : Save Draft\n");
		CHANGE_LOG.append("  - Workflow Form : Reject : Error if no comment\n");
    	CHANGE_LOG.append("\nV.1.0.21 --- (02/06/2016)\n");
		CHANGE_LOG.append("  - PR Workflow : Consult Process\n");
		CHANGE_LOG.append("  - Scheduler : Reset Sequence\n");
		CHANGE_LOG.append("  - AP UI : Initial\n");
		CHANGE_LOG.append("  - AV UI : Initial\n");
		CHANGE_LOG.append("  - PR Workflow : Show Real Requester\n");
		CHANGE_LOG.append("  - PR : Budget CC : Show Project Code\n");
		CHANGE_LOG.append("  - PR Workflow : Fill PR Doc Description\n");
		CHANGE_LOG.append("  - PR & PD : Change Date Format to 'dd/mm/yyyy'\n");
		CHANGE_LOG.append("  - Workflow History : Sort Ascending\n");
		CHANGE_LOG.append("  - Interface : Check Budget : Change Paramters\n");
    	CHANGE_LOG.append("\nV.1.0.20 --- (25/05/2016)\n");
		CHANGE_LOG.append("  - Workflow Service : Separate service for PR and PD\n");
		CHANGE_LOG.append("  - PR Workflow : Reviewer check Budget every level\n");
    	CHANGE_LOG.append("\nV.1.0.19 --- (24/05/2016)\n");
		CHANGE_LOG.append("  - PR Unit : Query only Active Unit\n");
		CHANGE_LOG.append("  - PD Boss : Only Employee 001509\n");
		CHANGE_LOG.append("  - PR Workflow : Consult Button\n");
    	CHANGE_LOG.append("\nV.1.0.18 --- (23/05/2016)\n");
		CHANGE_LOG.append("  - PR Form : Check Budget : Show Error if budget is not enough\n");
		CHANGE_LOG.append("  - Interface : Create PR : Change parameter\n");
		CHANGE_LOG.append("  - PR Form : Upload File : Add Description field\n");
    	CHANGE_LOG.append("\nV.1.0.17 --- (22/05/2016)\n");
		CHANGE_LOG.append("  - PR Workflow : Convert Employee Code with '0' padding\n");
		CHANGE_LOG.append("  - PD Worfklow  : Show Error Dialog box with xmlrpc parameter\n");
		CHANGE_LOG.append("  - PD Form  : Search Additional PR\n");
		CHANGE_LOG.append("  - PD Form  : Check Across Budget with total\n");
    	CHANGE_LOG.append("\nV.1.0.16 --- (19/05/2016)\n");
		CHANGE_LOG.append("  - PR Form : Set Focus in Dialog\n");
		CHANGE_LOG.append("  - PD Interface : Update Status\n");
		CHANGE_LOG.append("  - Interface : Check Budget\n");
		CHANGE_LOG.append("  - PR Form : Choose Budget Cc : change grid column header\n");
		CHANGE_LOG.append("  - PR Form : Limit Max Length for some text fields\n");
		CHANGE_LOG.append("  - WF Approved : Last Approver Signature\n");
		CHANGE_LOG.append("  - Interface : Create PR : if error then rollback\n");
		CHANGE_LOG.append("  - Doc Folder : Add Permission to Procurement Section\n");
    	CHANGE_LOG.append("\nV.1.0.15 --- (16/05/2016)\n");
		CHANGE_LOG.append("  - DB : Change field name : pcm_req.method -> pcm_req.prweb_method_id\n");
		CHANGE_LOG.append("  - PR Form : List mandatory fields\n");
    	CHANGE_LOG.append("\nV.1.0.14 --- (15/05/2016)\n");
		CHANGE_LOG.append("  - PR Form : Check file count if total >= 100,000\n");
		CHANGE_LOG.append("  - PR Form : Save Draft don't close form\n");
		CHANGE_LOG.append("  - PR Form : Resize grid when window resize\n");
		CHANGE_LOG.append("  - PD Interface : Accept Thai Characters\n");
    	CHANGE_LOG.append("\nV.1.0.13 --- (13/05/2016)\n");
		CHANGE_LOG.append("  - PR Workflow : Gen PR Pdf at the last approval\n");
		CHANGE_LOG.append("  - DB : Drop table pb2_pcm_ord_dtl\n");
		CHANGE_LOG.append("  - PR Pdf : Fill with data from the PR Form\n");
		CHANGE_LOG.append("  - PD Grid : Show Section Name\n");
		CHANGE_LOG.append("  - Preview Pdf : Change URL\n");
		CHANGE_LOG.append("  - PD Form : Show Workflow History\n");
    	CHANGE_LOG.append("\nV.1.0.12 --- (08/05/2016)\n");
		CHANGE_LOG.append("  - PR Workflow : Find Path\n");
		CHANGE_LOG.append("  - PR Form : Validate Procurement Method and Committee\n");
    	CHANGE_LOG.append("\nV.1.0.11 --- (06/05/2016)\n");
		CHANGE_LOG.append("  - SQL : change LIKE to ILIKE for case insensitive search\n");
		CHANGE_LOG.append("  - PR Form : Change Requester\n");
		CHANGE_LOG.append("  - PR Form : If select THB currency, disable currency rate text field\n");
		CHANGE_LOG.append("  - PR Form : Fixed Bug : Cannot Delete PR if ECM Folder does not exist\n");
		CHANGE_LOG.append("  - PR Form : Get Currency Rate Error Message\n");
		CHANGE_LOG.append("  - PR Form : Across Budget,Ref ID Check Box : Hide/Show Text Field\n");
		CHANGE_LOG.append("\nV.1.0.10 --- (05/05/2016)\n");
		CHANGE_LOG.append("  - WF Form : Update Task Share UI Data from Edited Data\n");
		CHANGE_LOG.append("  - Interface : Create PR\n");
		CHANGE_LOG.append("  - Interface : Update PR Status\n");
		CHANGE_LOG.append("  - Interface : Create PD\n");
		CHANGE_LOG.append("  - Main Menu : Change Caption\n");
		CHANGE_LOG.append("\nV.1.0.9 --- (30/04/2016)\n");
		CHANGE_LOG.append("  - WF Form : Workflow History : Currenct Task shows 'Procurement' instead of '-'\n");
		CHANGE_LOG.append("  - WF Form : Update My Task Title from Edited Data\n");
		CHANGE_LOG.append("  - WF Form : Hide Equipment Radio on Line Item Dialog\n");
		CHANGE_LOG.append("  - WF Form : Hide Stock Location\n");
		CHANGE_LOG.append("  - WF Form : Event Clear Button\n");
		CHANGE_LOG.append("\nV.1.0.8 --- (28/04/2016)\n");
		CHANGE_LOG.append("  - WF Form : Search Event Dialog\n");
		CHANGE_LOG.append("  - WF Form : Search Section and Project Dialog\n");
		CHANGE_LOG.append("\nV.1.0.7 --- (25/04/2016)\n");
		CHANGE_LOG.append("  - WF Share UI : Edit Button\n");
		CHANGE_LOG.append("  - PR Workflow : Find Procurement Boss\n");
		CHANGE_LOG.append("  - PR Form : Remove Field : 'Stock','Pcm Ou'\n");
		CHANGE_LOG.append("  - PR Form : Tab User : Fill User Information\n");
		CHANGE_LOG.append("\nV.1.0.6 --- (21/04/2016)\n");
		CHANGE_LOG.append("  - PR Grid : Workflow History\n");
		CHANGE_LOG.append("  - PR Form : Add Committee\n");
		CHANGE_LOG.append("  - PR : Gen ID from DB sequence and Fiscal Year\n");
		CHANGE_LOG.append("  - PR Form : Add Line Item\n");
		CHANGE_LOG.append("  - PR Form : Add Field prototype_contract_no\n");
		CHANGE_LOG.append("  - PR Form : Download Middle Price Document\n");
		CHANGE_LOG.append("  - PR Search : Show Grid Field Value\n");
		CHANGE_LOG.append("  - PR Form : Prototype Combo Box\n");
		CHANGE_LOG.append("  - WF Share UI : Remove 'Reassign' Button\n");
		CHANGE_LOG.append("  - PR Form : Tab Committee\n");
		CHANGE_LOG.append("  - PR Form : Currency Combo Box\n");
		CHANGE_LOG.append("  - PR Form : Line Item : Product Uom Combo Box\n");
		CHANGE_LOG.append("  - New Table : pb2_ext_product_uom, pb2_ext_res_currency, pb2_ext_res_currency_rate\n");
		CHANGE_LOG.append("  - Delete Approval Matrix Code and Tables\n");
		CHANGE_LOG.append("  - Change Code Prefix 'NSTDA' to 'PB'\n");
		CHANGE_LOG.append("  - Make Ext JS Theme Font larger\n");
		CHANGE_LOG.append("\nV.1.0.5 --- (14/03/2016)\n");
		CHANGE_LOG.append("  - Add Procurement Order Page\n");
		CHANGE_LOG.append("\nV.1.0.4 --- (03/03/2016)\n");
		CHANGE_LOG.append("  - Add Approval Feature\n");
		CHANGE_LOG.append("\nV.1.0.3 --- (29/02/2016)\n");
		CHANGE_LOG.append("  - Update PR Form : Add Detail, Committee\n");
		CHANGE_LOG.append("\nV.1.0.2 --- (24/02/2016)\n");
		CHANGE_LOG.append("  - Update PR Form\n");
		CHANGE_LOG.append("  - Create XML RPC URL for Odoo\n");
		CHANGE_LOG.append("\nV.1.0.1 --- (23/02/2016)\n");
		CHANGE_LOG.append("  - Update PR UI\n");
		CHANGE_LOG.append("\nV.1.0.0 --- (17/02/2016)\n");
		CHANGE_LOG.append("  - Initial");
    }
    
    public static final String TABLE_PREFIX = "pb2_";
    public static final String TABLE_EXT_PREFIX = TABLE_PREFIX + "ext_";
}
