package pb.repo.admin.constant;

public class AdminConstant {
	public static final StringBuffer CHANGE_LOG = new StringBuffer();
	
	public static final String VERSION = "1.0.85";
	
    static {
//		CHANGE_LOG.append("  - Interface : Use user_id to call service\n");
//		CHANGE_LOG.append("  - Interface : For Odoo : Manage Member in Accounting Group\n");
//		CHANGE_LOG.append("  - Workflow : Admin Adhoc Task\n");
//		CHANGE_LOG.append("  - Workflow History : Action and task : Multiple Languages\n");
//		CHANGE_LOG.append("  - PR Form : Additional PR : Get Old Committee as default\n");
//		CHANGE_LOG.append("  - AV : Add Field reason\n");
    	CHANGE_LOG.append("\nV."+AdminConstant.VERSION+" --- (26/10/2016)\n");
		CHANGE_LOG.append("  - AV,EX : Hide Carbon Footprint section\n");
		CHANGE_LOG.append("  - EX : Hide Import Attendee Button\n");
		CHANGE_LOG.append("  - EX : Add Field Description and Change Label\n");
		CHANGE_LOG.append("  - AV : Change Label\n");
		CHANGE_LOG.append("  - EX : Clear AV : Get Data from AV\n");
    	CHANGE_LOG.append("\nV.1.0.84 --- (26/10/2016)\n");
		CHANGE_LOG.append("  - PD : Change Attachment Description\n");
    	CHANGE_LOG.append("\nV.1.0.83 --- (25/10/2016)\n");
		CHANGE_LOG.append("  - Optimize Code\n");
		CHANGE_LOG.append("  - EX : Change Column AP Type to EX Type\n");
		CHANGE_LOG.append("  - PD Workflow Form : Remove Requester Field\n");
    	CHANGE_LOG.append("\nV.1.0.82 --- (17/10/2016)\n");
		CHANGE_LOG.append("  - Workflow Form : 2 Languages\n");
		CHANGE_LOG.append("  - My Task : 2 Languages\n");
		CHANGE_LOG.append("  - PR Pdf : Adjust\n");
		CHANGE_LOG.append("  - EX : Payment Type : Add Petty Cash\n");
    	CHANGE_LOG.append("\nV.1.0.82 --- (14/10/2016)\n");
		CHANGE_LOG.append("  - Approval Matrix : Project : Wrong Result\n");
    	CHANGE_LOG.append("\nV.1.0.81 --- (11/10/2016)\n");
		CHANGE_LOG.append("  - AV,EX : External Attendee : Add Field section\n");
		CHANGE_LOG.append("  - EX : Add Field reason for bypass procurement\n");
		CHANGE_LOG.append("  - PR,AV,EX Pdf : Adjust Org Name Length\n");
		CHANGE_LOG.append("  - PR Form : Change Fiscal Year Field to Combobox\n");
		CHANGE_LOG.append("  - AV Item : Add Fields\n");
		CHANGE_LOG.append("  - EX Share UI : Edit Attachment Description\n");
    	CHANGE_LOG.append("\nV.1.0.80 --- (06/10/2016)\n");
		CHANGE_LOG.append("  - PR,AV,EX Pdf : Budget Source\n");
		CHANGE_LOG.append("  - AV,EX Interface : Parameter Approve Date = now\n");
		CHANGE_LOG.append("  - AV,EX Pdf : Old AV : Add Field Objective\n");
		CHANGE_LOG.append("  - PR,AV,EX Pdf : Bold Label\n");
		CHANGE_LOG.append("  - AV,EX Pdf : Sign Last Approver\n");
    	CHANGE_LOG.append("\nV.1.0.79 --- (05/10/2016)\n");
		CHANGE_LOG.append("  - EX Interface : Change parameter advance_expense_id.id to advance_expense_number\n");
		CHANGE_LOG.append("  - PR Interface : Add History\n");
    	CHANGE_LOG.append("\nV.1.0.78 --- (04/10/2016)\n");
		CHANGE_LOG.append("  - EX : Payment Document\n");
    	CHANGE_LOG.append("\nV.1.0.77 --- (03/10/2016)\n");
		CHANGE_LOG.append("  - AV : Old AV : Clear Reason Field if change Requester\n");
		CHANGE_LOG.append("  - EX : Item : Select Activity Group before show Activity List\n");
		CHANGE_LOG.append("  - Workflow History : 2 Languages\n");
		CHANGE_LOG.append("  - EX : Duplicated Reviewer\n");
		CHANGE_LOG.append("  - EX : Warn : No Detail\n");
    	CHANGE_LOG.append("\nV.1.0.76 --- (30/09/2016)\n");
		CHANGE_LOG.append("  - System Config : PCM_REQ_TOP_GROUP, PCM_ORD_TOP_GROUP,EXP_BRW_TOP_GROUP, EXP_USE_TOP_GROUP\n");
		CHANGE_LOG.append("  - Workflow : Add Fields status_th\n");
		CHANGE_LOG.append("  - Workflow History : Add Fields action_th and task_th\n");
		CHANGE_LOG.append("  - Folder Path Name : Use A.D. instead of B.E.\n");
		CHANGE_LOG.append("  - AV,EX : Old AV : Query view pb2_av_outstanding_view\n");
    	CHANGE_LOG.append("\nV.1.0.75 --- (29/09/2016)\n");
		CHANGE_LOG.append("  - PR,AV,EX : Cannot Change Requester\n");
		CHANGE_LOG.append("  - Workflow History Interface\n");
		CHANGE_LOG.append("  - EX Pdf : Adjust\n");
    	CHANGE_LOG.append("\nV.1.0.74 --- (28/09/2016)\n");
		CHANGE_LOG.append("  - AV,EX : Copy : Missing fund_id\n");
		CHANGE_LOG.append("  - EX Interface : Create EX : not send bank if pay_type is 0 or 2\n");
		CHANGE_LOG.append("  - EX Pdf : not show bank radio value if pay_type is 0 or 2\n");
		CHANGE_LOG.append("  - EX Form : not enable bank controls if pay_type is 0 or 2\n");
		CHANGE_LOG.append("  - AV : Change Old AV Columns' Labels\n");
		CHANGE_LOG.append("  - AV Pdf : Before and After Save Draft are difference\n");
		CHANGE_LOG.append("  - AV : Change Old AV Columns' Labels\n");
		CHANGE_LOG.append("  - EX Pdf : not show supplier name\n");
		CHANGE_LOG.append("  - AV,EX Form : Set Status Field after Save Draft\n");
		CHANGE_LOG.append("  - Budget Source Dialog : Remove Columne Cost Center\n");
		CHANGE_LOG.append("  - AV Interface : Wrong date_back value\n");
    	CHANGE_LOG.append("\nV.1.0.73 --- (22/09/2016)\n");
		CHANGE_LOG.append("  - EX : Workflow Form : Pay Type Label\n");
		CHANGE_LOG.append("  - EX : Edit Attached Files Description\n");
		CHANGE_LOG.append("  - AV : Gen Pdf\n");
		CHANGE_LOG.append("  - EX : Gen Pdf\n");
		CHANGE_LOG.append("  - My Task : Hide Icon\n");
		CHANGE_LOG.append("  - AV : Search Error\n");
    	CHANGE_LOG.append("\nV.1.0.72 --- (20/09/2016)\n");
		CHANGE_LOG.append("  - EX : Copy : No Attendee\n");
		CHANGE_LOG.append("  - EX : Supplier Name not show\n");
		CHANGE_LOG.append("  - EX : Source of Fund\n");
		CHANGE_LOG.append("  - EX : Other bank not show\n");
		CHANGE_LOG.append("  - EX : Add Activity Group Column in grid\n");
    	CHANGE_LOG.append("\nV.1.0.71 --- (19/09/2016)\n");
		CHANGE_LOG.append("  - AV,EX : Smart Search Bank Name\n");
		CHANGE_LOG.append("  - PR,AV,EX : Improve Cost Control Query\n");
		CHANGE_LOG.append("  - EX : Save Wrong Pay Type\n");
    	CHANGE_LOG.append("\nV.1.0.70 --- (14/09/2016)\n");
		CHANGE_LOG.append("  - AV Interface : Add Parameters\n");
		CHANGE_LOG.append("  - EX Workflow Form : Edit Rejected EX\n");
		CHANGE_LOG.append("  - EX Interface : Add Parameters\n");
		CHANGE_LOG.append("  - EX Item : Add Field act_grp_id\n");
		CHANGE_LOG.append("  - EX Item : Change Field activity_id to act_id\n");
		CHANGE_LOG.append("  - EX Form : Line Item : Remove Field vat\n");
		CHANGE_LOG.append("  - EX : Remove Field vat, vat_id, req_section_id\n");
		CHANGE_LOG.append("  - EX Form : Payment Method : Remove one option\n");
		CHANGE_LOG.append("  - AV Form : Choose Advance Type than show date_back\n");
		CHANGE_LOG.append("  - Change view name : pb2_ext_pr_method_committee_view to pb2_pr_method_committee_view\n");
		CHANGE_LOG.append("  - Change view name : pb2_ext_pr_method_view to pb2_pr_method_view\n");
		CHANGE_LOG.append("  - AV : Change field name : cost_control_to to date_back\n");
		CHANGE_LOG.append("  - AV : Remove field : req_section_id,cost_control, cost_control_from\n");
		CHANGE_LOG.append("  - PR : Add Multiple Committee\n");
    	CHANGE_LOG.append("\nV.1.0.69 --- (13/09/2016)\n");
		CHANGE_LOG.append("  - Odoo : Query Active Currency\n");
		CHANGE_LOG.append("  - Odoo : Query Active Account Tax\n");
		CHANGE_LOG.append("  - Odoo : Query Active User\n");
		CHANGE_LOG.append("  - EX Workflow Form : Adjust Fields\n");
		CHANGE_LOG.append("  - EX Form : Attendee Tab : 2 Languages\n");
		CHANGE_LOG.append("  - AV PDF : Add Field Cost Control\n");
		CHANGE_LOG.append("  - PR Interface : Create PR : change fiscal_year_id to fiscalyear_id\n");
    	CHANGE_LOG.append("\nV.1.0.68 --- (11/09/2016)\n");
		CHANGE_LOG.append("  - PR PDF : show fund_id\n");
		CHANGE_LOG.append("  - AP Form : Attendee Tab : 2 Languages\n");
		CHANGE_LOG.append("  - AP : Edit : Budget Source show [code]\n");
		CHANGE_LOG.append("  - AP : Requester : Show Title\n");
		CHANGE_LOG.append("  - AV : Add Field Cost Control\n");
		CHANGE_LOG.append("  - AV,AP : Interface\n");
		CHANGE_LOG.append("  - AP : Start Workflow\n");
    	CHANGE_LOG.append("\nV.1.0.67 --- (08/09/2016)\n");
		CHANGE_LOG.append("  - AV,AP : Edit : Show fund_id\n");
		CHANGE_LOG.append("  - AV Form : Participant : Show Title\n");
		CHANGE_LOG.append("  - AV,AP Attendee : Add Field title\n");
		CHANGE_LOG.append("  - PR : Search Project without PM\n");
    	CHANGE_LOG.append("\nV.1.0.66 --- (07/09/2016)\n");
		CHANGE_LOG.append("  - AV : Add System Config : MAIN_INF_AV_CREATE_AV\n");
		CHANGE_LOG.append("  - AV Workflow Form : Change Field Label\n");
		CHANGE_LOG.append("  - AV UI : Support 2 Languages\n");
		CHANGE_LOG.append("  - AV Workflow History : Missing ReqBy in Path\n");
		CHANGE_LOG.append("  - AV Form : Validate on Create Event\n");
		CHANGE_LOG.append("  - PR Interface : Create PR : Add Field fund_id\n");
		CHANGE_LOG.append("  - AV,EX : Add Field fund_id\n");
    	CHANGE_LOG.append("\nV.1.0.65 --- (05/09/2016)\n");
		CHANGE_LOG.append("  - PR : Add Field fund_id\n");
		CHANGE_LOG.append("  - Share UI : Hide Customize Dashboard Button\n");
    	CHANGE_LOG.append("\nV.1.0.64 --- (02/09/2016)\n");
		CHANGE_LOG.append("  - Folder Icon : Use Ext JS Dialog\n");
    	CHANGE_LOG.append("\nV.1.0.63 --- (01/09/2016)\n");
		CHANGE_LOG.append("  - PR Pdf : Remove border of total field\n");
		CHANGE_LOG.append("  - PR Form : ReqBy Dialog : Search short_name field\n");
		CHANGE_LOG.append("  - Workflow Form : Make Consult Chooser dialog look like ReqBy Dialog\n");
    	CHANGE_LOG.append("\nV.1.0.62 --- (30/08/2016)\n");
		CHANGE_LOG.append("  - PR Form : Validate Fiscal Year field in line item\n");
		CHANGE_LOG.append("  - PD Interface : Add Permission to Attached PR Folder\n");
		CHANGE_LOG.append("  - PR Form : Change ReqBy Dialog Column Format\n");
		CHANGE_LOG.append("  - PR Form : Change Employee Committee Dialog as same as ReqBy Dialog\n");
    	CHANGE_LOG.append("\nV.1.0.61 --- (29/08/2016)\n");
		CHANGE_LOG.append("  - PR Form : Add Field TotalCnv\n");
		CHANGE_LOG.append("  - PR Detail : Remove Field PriceCnv, isEquipment\n");
    	CHANGE_LOG.append("\nV.1.0.60 --- (28/08/2016)\n");
		CHANGE_LOG.append("  - PR Form : Validate Fields on Create Event\n");
		CHANGE_LOG.append("  - PR Form : Add title to requester and preparer\n");
    	CHANGE_LOG.append("\nV.1.0.59 --- (27/08/2016)\n");
		CHANGE_LOG.append("  - PR,AV,AP Form : Move Field Budget Source to the first position\n");
		CHANGE_LOG.append("  - PD Interface : Create PD : Attache File Size 0\n");
    	CHANGE_LOG.append("\nV.1.0.58 --- (25/08/2016)\n");
		CHANGE_LOG.append("  - PR Interface : Login by admin\n");
		CHANGE_LOG.append("  - PR Pdf : Adjust Fields\n");
    	CHANGE_LOG.append("\nV.1.0.57 --- (24/08/2016)\n");
		CHANGE_LOG.append("  - PR Line Item : Add fiscal_year field\n");
		CHANGE_LOG.append("  - PR Pdf : Adjust Fields\n");
		CHANGE_LOG.append("  - AV Search : Workflow History\n");
		CHANGE_LOG.append("  - Table workflow history : Add Field status\n");
		CHANGE_LOG.append("  - AV Workflow : Add Expense Officer into Path\n");
    	CHANGE_LOG.append("\nV.1.0.55 --- (22/08/2016)\n");
		CHANGE_LOG.append("  - AV : Start Workflow\n");
    	CHANGE_LOG.append("\nV.1.0.54 --- (20/08/2016)\n");
		CHANGE_LOG.append("  - PR Form : Change Field Labels\n");
    	CHANGE_LOG.append("\nV.1.0.53 --- (18/08/2016)\n");
		CHANGE_LOG.append("  - PR Form : Add Contract Date Field\n");
    	CHANGE_LOG.append("\nV.1.0.52 --- (17/08/2016)\n");
		CHANGE_LOG.append("  - PR Form : Budget Status UI\n");
		CHANGE_LOG.append("  - PD Workflow Form : Add Consult Button\n");
    	CHANGE_LOG.append("\nV.1.0.51 --- (16/08/2016)\n");
		CHANGE_LOG.append("  - Search Employee : Ignore 'admin'\n");
		CHANGE_LOG.append("  - PR Form : Edit : Budget Source : Wrong Language\n");
		CHANGE_LOG.append("  - PR Form : Edit : Committee : Wrong Language\n");
		CHANGE_LOG.append("  - PR Search : Thai Columns\n");
		CHANGE_LOG.append("  - PR Interface : Change user from admin to current user\n");
    	CHANGE_LOG.append("\nV.1.0.50 --- (15/08/2016)\n");
		CHANGE_LOG.append("  - PR Form : User Tab : 2 Languages\n");
		CHANGE_LOG.append("  - PR Form : Search User : 2 Languages\n");
		CHANGE_LOG.append("  - PR Form : Committee Tab : 2 Languages\n");
		CHANGE_LOG.append("  - PR Committee : Add Field Title\n");
		CHANGE_LOG.append("  - PR Form : Search Committee : 2 Languages\n");
		CHANGE_LOG.append("  - PR Form : Objective Type and Reason : 2 Languages\n");
		CHANGE_LOG.append("  - PR Workflow : Add Procument Org Member Folder Permission\n");
		CHANGE_LOG.append("  - Workflow Form : View in browser\n");
		CHANGE_LOG.append("  - PR Pdf : Thai Fields\n");
    	CHANGE_LOG.append("\nV.1.0.49 --- (08/08/2016)\n");
		CHANGE_LOG.append("  - PR Pdf : Add Activity Group\n");
		CHANGE_LOG.append("  - PR Line Item : Edit Activity Group\n");
		CHANGE_LOG.append("  - Search Budget Source : 2 Languages\n");
		CHANGE_LOG.append("  - PR Form : Clear Across Budget when check Additional PR\n");
    	CHANGE_LOG.append("\nV.1.0.48 --- (08/08/2016)\n");
		CHANGE_LOG.append("  - PR Workflow Form : Edit File Description\n");
		CHANGE_LOG.append("  - AP Activity Combo Box : Google Search Style\n");
		CHANGE_LOG.append("  - Cost Control Combo Box : 2 Languages\n");
		CHANGE_LOG.append("  - PR Line Item : Add Activity Group Field\n");
    	CHANGE_LOG.append("\nV.1.0.47 --- (03/08/2016)\n");
		CHANGE_LOG.append("  - PR Workflow : Resubmit create multiple next action record\n");
		CHANGE_LOG.append("  - PR Form : Additional PR : Search PR that got same purchasing type\n");
		CHANGE_LOG.append("  - PR,AV,AP Form : Multiple file upload\n");
		CHANGE_LOG.append("  - PR Budget Source : Change Hint Message\n");
		CHANGE_LOG.append("  - PR Objective : Add Hint Message\n");
		CHANGE_LOG.append("  - Odoo : Change DB to V.5\n");
    	CHANGE_LOG.append("\nV.1.0.46 --- (01/08/2016)\n");
		CHANGE_LOG.append("  - PR Form : Reason field : Change from text to combobox\n");
		CHANGE_LOG.append("  - PR Form : File Description : Edit Button\n");
		CHANGE_LOG.append("  - PR Form : Additional PR : Search PR that not referenced by Other PR\n");
		CHANGE_LOG.append("  - PR Form : VAT : Change SQL\n");
    	CHANGE_LOG.append("\nV.1.0.45 --- (28/07/2016)\n");
		CHANGE_LOG.append("  - Workflow Error Msg : Change by current language\n");
    	CHANGE_LOG.append("\nV.1.0.44 --- (28/07/2016)\n");
		CHANGE_LOG.append("  - PR Interface : Change Parameter objective_type to method_type\n");
		CHANGE_LOG.append("  - PR Pdf : Adjust Layout\n");
		CHANGE_LOG.append("  - PD Resubmit : Missing Approver in History\n");
    	CHANGE_LOG.append("\nV.1.0.43 --- (27/07/2016)\n");
		CHANGE_LOG.append("  - PR Form : Committee : Delete until 1 committee left, App shows wrong position\n");
		CHANGE_LOG.append("  - Budget Source : Project : Show PM's name after selected language\n");
		CHANGE_LOG.append("  - Workflow History : Show User name after selected language\n");
		CHANGE_LOG.append("  - View in browser : Add file name after URL\n");
		CHANGE_LOG.append("  - Interface PR : Budget Source : Project : Send Wrong Value\n");
		CHANGE_LOG.append("  - PR : Resubmit with difference total, don't get new approval matrix\n");
		CHANGE_LOG.append("  - Workflow Share UI : Search Consult Button not work\n");
		CHANGE_LOG.append("  - PR,PD Pdf : Thai Name Signatures\n");
    	CHANGE_LOG.append("\nV.1.0.42 --- (21/07/2016)\n");
		CHANGE_LOG.append("  - PR Approval Matrix : Project Type\n");
		CHANGE_LOG.append("  - PR Form : Committee : Chairman Label\n");
		CHANGE_LOG.append("  - PR Form : Edit : Enable Currency Rate field if it is not 'THB'\n");
		CHANGE_LOG.append("  - PR Form : Additional PR : Clear Ref PR No. field if uncheck the checkbox\n");
    	CHANGE_LOG.append("\nV.1.0.41 --- (20/07/2016)\n");
		CHANGE_LOG.append("  - PD Interface : Action=1 : Check duplicated data\n");
		CHANGE_LOG.append("  - PD Interface : Action=3 : Remove Approver from History\n");
		CHANGE_LOG.append("  - Workflow : Tell the reason for rejecting in the comment field\n");
		CHANGE_LOG.append("  - PR Interface : Send Price instead of Converted Price\n");
		CHANGE_LOG.append("  - PD Workflow : Last Approver signature\n");
		CHANGE_LOG.append("  - PD Interface : Add Approver Permission to PD Folder\n");
    	CHANGE_LOG.append("\nV.1.0.40 --- (15/07/2016)\n");
		CHANGE_LOG.append("  - PR Form : User Tab : Multiple Language Label\n");
		CHANGE_LOG.append("  - PD Workflow : Add Approver into history\n");
    	CHANGE_LOG.append("\nV.1.0.39 --- (13/07/2016)\n");
		CHANGE_LOG.append("  - PR Form : Check Duplicated Committee\n");
		CHANGE_LOG.append("  - AV Interface : Fill Parameters from UI Input\n");
		CHANGE_LOG.append("  - UI : Multiple Languages\n");
    	CHANGE_LOG.append("\nV.1.0.38 --- (12/07/2016)\n");
		CHANGE_LOG.append("  - PR Form : Error Msg\n");
    	CHANGE_LOG.append("\nV.1.0.37 --- (12/07/2016)\n");
		CHANGE_LOG.append("  - AV Form : List Old AV\n");
		CHANGE_LOG.append("  - PD Interface : Change method from create to action\n");
    	CHANGE_LOG.append("\nV.1.0.36 --- (12/07/2016)\n");
		CHANGE_LOG.append("  - PR Form : Check Mandatory Equiment field\n");
		CHANGE_LOG.append("  - PR Form : Update Error Messages\n");
		CHANGE_LOG.append("  - PD Interface : Add Comment Field\n");
    	CHANGE_LOG.append("\nV.1.0.35 --- (11/07/2016)\n");
		CHANGE_LOG.append("  - PR Interface : Add Reason field\n");
		CHANGE_LOG.append("  - AV Form : Update table detail\n");
		CHANGE_LOG.append("  - AV : Remove field activity\n");
    	CHANGE_LOG.append("\nV.1.0.34 --- (08/07/2016)\n");
		CHANGE_LOG.append("  - PR,AV,AP Form : Change Budget Source Label\n");
		CHANGE_LOG.append("  - PR Form : Change Across Budget Label\n");
		CHANGE_LOG.append("  - PR Form : Change Location Label\n");
		CHANGE_LOG.append("  - PR Form : Change Old PR Label\n");
		CHANGE_LOG.append("  - PR Form : Change Price Label\n");
		CHANGE_LOG.append("  - PR,AV,AP Form : Budget Source : Main Equipment Explanation icon\n");
		CHANGE_LOG.append("  - AV : Add table detail\n");
    	CHANGE_LOG.append("\nV.1.0.33 --- (07/07/2016)\n");
		CHANGE_LOG.append("  - AV Form : Change Activity Combo Box to Text Area\n");
		CHANGE_LOG.append("  - AV Table : Change Activity Field Type from integer to varchar\n");
		CHANGE_LOG.append("  - PD Workflow : Comment History : Remove Doc Type from Comment\n");
		CHANGE_LOG.append("  - PR Form : Cross Year Budget : Filter Purchase Method\n");
    	CHANGE_LOG.append("\nV.1.0.32 --- (06/07/2016)\n");
		CHANGE_LOG.append("  - Main : Change MAIN_ODOO_URL and MAIN_ODOO_DB to PCM_* and EXP_*\n");
		CHANGE_LOG.append("  - PR Form : Line Item : Remove 'Type' Column\n");
		CHANGE_LOG.append("  - Interface : Create AV\n");
		CHANGE_LOG.append("  - AV,AP : Add Column employee position id for Interface\n");
		CHANGE_LOG.append("  - PR Interface : delete parameter purchase_confidential_id.id\n");
		CHANGE_LOG.append("  - PR Interface : change parameter confidential_detail to purchase_condition_detail\n");
    	CHANGE_LOG.append("\nV.1.0.31 --- (05/07/2016)\n");
		CHANGE_LOG.append("  - PD Interface : Resubmit and cancel from Odoo\n");
		CHANGE_LOG.append("  - PR Form : Read Method Cond2 from table\n");
    	CHANGE_LOG.append("\nV.1.0.30 --- (30/06/2016)\n");
		CHANGE_LOG.append("  - Workflow Table : add field 'execution_id'\n");
		CHANGE_LOG.append("  - Admin : System Config : MAIN_INF_PD_UPDATE_STATUS\n");
		CHANGE_LOG.append("  - AP : Copy : Clear Employee AV : Clear AV Id\n");
		CHANGE_LOG.append("  - AV,AP Form : Add Requester Tel NO. field\n");
    	CHANGE_LOG.append("\nV.1.0.29 --- (27/06/2016)\n");
		CHANGE_LOG.append("  - PD : Search Approval Matrix\n");
    	CHANGE_LOG.append("\nV.1.0.28 --- (22/06/2016)\n");
		CHANGE_LOG.append("  - Consult : Comment Required\n");
		CHANGE_LOG.append("  - PR : Send for Approval : Missing Attached Files\n");
		CHANGE_LOG.append("  - PR Form : Add Field Request Tel NO.\n");
		CHANGE_LOG.append("  - PR Pdf : Add Field Request Tel NO.\n");
    	CHANGE_LOG.append("\nV.1.0.27 --- (21/06/2016)\n");
		CHANGE_LOG.append("  - PR,AV,AP Form : Search Section : Add Column Cost Center\n");
		CHANGE_LOG.append("  - AP Form : Change comply to meeting requirement\n");
		CHANGE_LOG.append("  - Search : Google Style\n");
		CHANGE_LOG.append("  - PR : Change Committee Input Dialog\n");
    	CHANGE_LOG.append("\nV.1.0.26 --- (14/06/2016)\n");
		CHANGE_LOG.append("  - AP Form : Preview\n");
		CHANGE_LOG.append("  - AV Form : Preview\n");
		CHANGE_LOG.append("  - Main Menu : Change Labels\n");
		CHANGE_LOG.append("  - Interface : Create PR Interface : Wrong Assignee\n");
    	CHANGE_LOG.append("\nV.1.0.25 --- (13/06/2016)\n");
		CHANGE_LOG.append("  - AP Form : Activity Detail is not mandatory if no choice to select\n");
		CHANGE_LOG.append("  - AP Form : Edit Activity\n");
    	CHANGE_LOG.append("\nV.1.0.24 --- (10/06/2016)\n");
		CHANGE_LOG.append("  - AP Form : Tab Attendee : Show Cost Control\n");
		CHANGE_LOG.append("  - AP Form : Tab Info : Combo Boxes don't show Bank list\n");
    	CHANGE_LOG.append("\nV.1.0.23 --- (09/06/2016)\n");
		CHANGE_LOG.append("  - AP Form : Save Draft\n");
		CHANGE_LOG.append("  - AV Form : Copy AV Button\n");
    	CHANGE_LOG.append("\nV.1.0.22 --- (07/06/2016)\n");
		CHANGE_LOG.append("  - AV Form : Save Draft\n");
		CHANGE_LOG.append("  - Workflow Form : Reject : Error if no comment\n");
    	CHANGE_LOG.append("\nV.1.0.21 --- (02/06/2016)\n");
		CHANGE_LOG.append("  - PR Workflow : Consult Process\n");
		CHANGE_LOG.append("  - Scheduler : Reset Sequence\n");
		CHANGE_LOG.append("  - AP UI : Initial\n");
		CHANGE_LOG.append("  - AV UI : Initial\n");
		CHANGE_LOG.append("  - PR Workflow : Show Real Requester\n");
		CHANGE_LOG.append("  - PR : Budget CC : Show Project Code\n");
		CHANGE_LOG.append("  - PR Workflow : Fill PR Doc Description\n");
		CHANGE_LOG.append("  - PR & PD : Change Date Format to 'dd/mm/yyyy'\n");
		CHANGE_LOG.append("  - Workflow History : Sort Ascending\n");
		CHANGE_LOG.append("  - Interface : Check Budget : Change Paramters\n");
    	CHANGE_LOG.append("\nV.1.0.20 --- (25/05/2016)\n");
		CHANGE_LOG.append("  - Workflow Service : Separate service for PR and PD\n");
		CHANGE_LOG.append("  - PR Workflow : Reviewer check Budget every level\n");
    	CHANGE_LOG.append("\nV.1.0.19 --- (24/05/2016)\n");
		CHANGE_LOG.append("  - PR Unit : Query only Active Unit\n");
		CHANGE_LOG.append("  - PD Boss : Only Employee 001509\n");
		CHANGE_LOG.append("  - PR Workflow : Consult Button\n");
    	CHANGE_LOG.append("\nV.1.0.18 --- (23/05/2016)\n");
		CHANGE_LOG.append("  - PR Form : Check Budget : Show Error if budget is not enough\n");
		CHANGE_LOG.append("  - Interface : Create PR : Change parameter\n");
		CHANGE_LOG.append("  - PR Form : Upload File : Add Description field\n");
    	CHANGE_LOG.append("\nV.1.0.17 --- (22/05/2016)\n");
		CHANGE_LOG.append("  - PR Workflow : Convert Employee Code with '0' padding\n");
		CHANGE_LOG.append("  - PD Worfklow  : Show Error Dialog box with xmlrpc parameter\n");
		CHANGE_LOG.append("  - PD Form  : Search Additional PR\n");
		CHANGE_LOG.append("  - PD Form  : Check Across Budget with total\n");
    	CHANGE_LOG.append("\nV.1.0.16 --- (19/05/2016)\n");
		CHANGE_LOG.append("  - PR Form : Set Focus in Dialog\n");
		CHANGE_LOG.append("  - PD Interface : Update Status\n");
		CHANGE_LOG.append("  - Interface : Check Budget\n");
		CHANGE_LOG.append("  - PR Form : Choose Budget Cc : change grid column header\n");
		CHANGE_LOG.append("  - PR Form : Limit Max Length for some text fields\n");
		CHANGE_LOG.append("  - WF Approved : Last Approver Signature\n");
		CHANGE_LOG.append("  - Interface : Create PR : if error then rollback\n");
		CHANGE_LOG.append("  - Doc Folder : Add Permission to Procurement Section\n");
    	CHANGE_LOG.append("\nV.1.0.15 --- (16/05/2016)\n");
		CHANGE_LOG.append("  - DB : Change field name : pcm_req.method -> pcm_req.prweb_method_id\n");
		CHANGE_LOG.append("  - PR Form : List mandatory fields\n");
    	CHANGE_LOG.append("\nV.1.0.14 --- (15/05/2016)\n");
		CHANGE_LOG.append("  - PR Form : Check file count if total >= 100,000\n");
		CHANGE_LOG.append("  - PR Form : Save Draft don't close form\n");
		CHANGE_LOG.append("  - PR Form : Resize grid when window resize\n");
		CHANGE_LOG.append("  - PD Interface : Accept Thai Characters\n");
    	CHANGE_LOG.append("\nV.1.0.13 --- (13/05/2016)\n");
		CHANGE_LOG.append("  - PR Workflow : Gen PR Pdf at the last approval\n");
		CHANGE_LOG.append("  - DB : Drop table pb2_pcm_ord_dtl\n");
		CHANGE_LOG.append("  - PR Pdf : Fill with data from the PR Form\n");
		CHANGE_LOG.append("  - PD Grid : Show Section Name\n");
		CHANGE_LOG.append("  - Preview Pdf : Change URL\n");
		CHANGE_LOG.append("  - PD Form : Show Workflow History\n");
    	CHANGE_LOG.append("\nV.1.0.12 --- (08/05/2016)\n");
		CHANGE_LOG.append("  - PR Workflow : Find Path\n");
		CHANGE_LOG.append("  - PR Form : Validate Procurement Method and Committee\n");
    	CHANGE_LOG.append("\nV.1.0.11 --- (06/05/2016)\n");
		CHANGE_LOG.append("  - SQL : change LIKE to ILIKE for case insensitive search\n");
		CHANGE_LOG.append("  - PR Form : Change Requester\n");
		CHANGE_LOG.append("  - PR Form : If select THB currency, disable currency rate text field\n");
		CHANGE_LOG.append("  - PR Form : Fixed Bug : Cannot Delete PR if ECM Folder does not exist\n");
		CHANGE_LOG.append("  - PR Form : Get Currency Rate Error Message\n");
		CHANGE_LOG.append("  - PR Form : Across Budget,Ref ID Check Box : Hide/Show Text Field\n");
		CHANGE_LOG.append("\nV.1.0.10 --- (05/05/2016)\n");
		CHANGE_LOG.append("  - WF Form : Update Task Share UI Data from Edited Data\n");
		CHANGE_LOG.append("  - Interface : Create PR\n");
		CHANGE_LOG.append("  - Interface : Update PR Status\n");
		CHANGE_LOG.append("  - Interface : Create PD\n");
		CHANGE_LOG.append("  - Main Menu : Change Caption\n");
		CHANGE_LOG.append("\nV.1.0.9 --- (30/04/2016)\n");
		CHANGE_LOG.append("  - WF Form : Workflow History : Currenct Task shows 'Procurement' instead of '-'\n");
		CHANGE_LOG.append("  - WF Form : Update My Task Title from Edited Data\n");
		CHANGE_LOG.append("  - WF Form : Hide Equipment Radio on Line Item Dialog\n");
		CHANGE_LOG.append("  - WF Form : Hide Stock Location\n");
		CHANGE_LOG.append("  - WF Form : Event Clear Button\n");
		CHANGE_LOG.append("\nV.1.0.8 --- (28/04/2016)\n");
		CHANGE_LOG.append("  - WF Form : Search Event Dialog\n");
		CHANGE_LOG.append("  - WF Form : Search Section and Project Dialog\n");
		CHANGE_LOG.append("\nV.1.0.7 --- (25/04/2016)\n");
		CHANGE_LOG.append("  - WF Share UI : Edit Button\n");
		CHANGE_LOG.append("  - PR Workflow : Find Procurement Boss\n");
		CHANGE_LOG.append("  - PR Form : Remove Field : 'Stock','Pcm Ou'\n");
		CHANGE_LOG.append("  - PR Form : Tab User : Fill User Information\n");
		CHANGE_LOG.append("\nV.1.0.6 --- (21/04/2016)\n");
		CHANGE_LOG.append("  - PR Grid : Workflow History\n");
		CHANGE_LOG.append("  - PR Form : Add Committee\n");
		CHANGE_LOG.append("  - PR : Gen ID from DB sequence and Fiscal Year\n");
		CHANGE_LOG.append("  - PR Form : Add Line Item\n");
		CHANGE_LOG.append("  - PR Form : Add Field prototype_contract_no\n");
		CHANGE_LOG.append("  - PR Form : Download Middle Price Document\n");
		CHANGE_LOG.append("  - PR Search : Show Grid Field Value\n");
		CHANGE_LOG.append("  - PR Form : Prototype Combo Box\n");
		CHANGE_LOG.append("  - WF Share UI : Remove 'Reassign' Button\n");
		CHANGE_LOG.append("  - PR Form : Tab Committee\n");
		CHANGE_LOG.append("  - PR Form : Currency Combo Box\n");
		CHANGE_LOG.append("  - PR Form : Line Item : Product Uom Combo Box\n");
		CHANGE_LOG.append("  - New Table : pb2_ext_product_uom, pb2_ext_res_currency, pb2_ext_res_currency_rate\n");
		CHANGE_LOG.append("  - Delete Approval Matrix Code and Tables\n");
		CHANGE_LOG.append("  - Change Code Prefix 'NSTDA' to 'PB'\n");
		CHANGE_LOG.append("  - Make Ext JS Theme Font larger\n");
		CHANGE_LOG.append("\nV.1.0.5 --- (14/03/2016)\n");
		CHANGE_LOG.append("  - Add Procurement Order Page\n");
		CHANGE_LOG.append("\nV.1.0.4 --- (03/03/2016)\n");
		CHANGE_LOG.append("  - Add Approval Feature\n");
		CHANGE_LOG.append("\nV.1.0.3 --- (29/02/2016)\n");
		CHANGE_LOG.append("  - Update PR Form : Add Detail, Committee\n");
		CHANGE_LOG.append("\nV.1.0.2 --- (24/02/2016)\n");
		CHANGE_LOG.append("  - Update PR Form\n");
		CHANGE_LOG.append("  - Create XML RPC URL for Odoo\n");
		CHANGE_LOG.append("\nV.1.0.1 --- (23/02/2016)\n");
		CHANGE_LOG.append("  - Update PR UI\n");
		CHANGE_LOG.append("\nV.1.0.0 --- (17/02/2016)\n");
		CHANGE_LOG.append("  - Initial");
    }
    
    public static final String TABLE_PREFIX = "pb2_";
    public static final String TABLE_EXT_PREFIX = TABLE_PREFIX + "ext_";
}
